export const GET_ERRORS = "GET_ERRORS";
export const GET_CITIES = "GET_CITIES";
export const CITIES_LOADING = "CITIES_LOADING";
export const CLEAR_CITIES = "CLEAR_CITIES";
export const SUCCESS_REGISTRATION_DISPATCH = "SUCCESS_REGISTRATION_DISPATCH";
