export const GET_ERRORS = "GET_ERRORS";
export const GET_CITIES = "GET_CITIES";
export const SUCCESS_REGISTRATION_DISPATCH = "SUCCESS_REGISTRATION_DISPATCH";
export const GET_MYTINERARIES_BY_CITY = "GET_MYTINERARIES_BY_CITY";
export const GET_ALL_MYTINERARIES = "GET_ALL_MYTINERARIES";
export const GET_ACTIVITIES_BY_MYTINERARY = "GET_ACTIVITIES_BY_MYTINERARY";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
